services:
  server:
    build: .
    volumes:
      - data:/databases
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src


volumes:
  data: